api_development:
  dialect: postgres
  database: idx_investing_tools_api_development
  user: postgres
  password: postgres
  host: 127.0.0.1
  pool: 5

tools_development:
  dialect: postgres
  database: idx_investing_tools_development
  user: postgres
  password: postgres
  host: 127.0.0.1
  pool: 5